imp_hostname: 'imp.nonsense.ws'
pot_hostname: 'pot.nonsense.ws'
sip_hostname: 'sip.nonsense.ws'
cloud_hostname: 'cloudforest.ws'
treehouse_hostname: 'kame.shaos.ws'
consul_hostname: 'consul.shaos.ws'
circus_hostname: 'circus.shaos.ws'
